### ISSUE TITLE
Callback construction doesn't work upon server restart / 1.2.0 breaks things

### ISSUE THREAD

**Issue by satyavh** [VeliovGroup/Meteor-Mailer#4]
I updated this package and things started breaking:

For example, this 'callback cbKey' construction breaks as soon as the server restarts (actually this was always an issue)

```
      @callbacks[cbKey] = callback

    _id = mailQueue.insert
      uid:      @uid
      opts:     opts
      to:       opts.to
      subject:  opts.subject
      template: opts.template
      sendAt:   opts.sendAt
      isSent:   false
      tries:    0
      callback: cbKey
```

The @callback[] array will be lost after restart, which means all the references in the collection to the callback will be incorrect, causing errors and mails not being send out! Bad idea

But you included a new check on line 84 `_self.callbacks[letter.callback]`. It now causes this error:

```
I20161031-14:19:17.276(1)? Trying to send email to example<email@example.com> again for NaN time(s)
I20161031-14:19:17.277(1)? Exception in defer callback: TypeError: _self.callbacks[letter.callback] is not a function
I20161031-14:19:17.277(1)?     at packages/ostrio_mailer.js:216:47
I20161031-14:19:17.278(1)?     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
I20161031-14:19:17.278(1)?     at packages/meteor.js:445:45
I20161031-14:19:17.278(1)?     at runWithEnvironment (packages/meteor.js:1176:24)
```

when I log out 'error' from `(error, success, recipient) ->` I get:
`
{ error: [TypeError: Cannot read property 'length' of null] }
`

which I suspect refers to the same line/issue - as email gets delivered fine using 1.1.0 and I don't see any changes in the API.

**Comment by dr-dimitru** [comment]
Hey @satyavh ,

Thank you for report, actually updated version was hanging around my SSD for last few month, waiting for release. Your message was a good reason.

Could you please update to [v1.2.1](https://github.com/VeliovGroup/Meteor-Mailer/releases/tag/1.2.1), and check this issue on your end?

**Comment by dr-dimitru** [comment]
@satyavh added a notice/explanation for send's `callback` - https://github.com/VeliovGroup/Meteor-Mailer/commit/17b635b37c904e024fdb43d743c66787bf107609

**Comment by satyavh** [comment]
It's a little better, but I still have this error that I didn't have with 1.1.x

```
I20161031-15:43:33.092(1)? Email wasn't sent to example<email@example.com> [TypeError: Cannot read property 'length' of null]
I20161031-15:43:33.092(1)? Trying to send email to example<email@example.com> again for 1 time(s)
```

I have no idea where this error comes from. Perhaps you see it:

My init:

```
  Meteor.mail = new Meteor.Mailer
    login: "[.....]"
    host: "[.....]"
    connectionUrl: "[.....]"
    accountName:  "[.....]"
    intervalTime: 5
    verbose: true
```

Send function:

```
    Meteor.mail.send
      to: accountName + '<' + invite.email + '>',
      subject: name + " invited you to join " + accountName + " at PostSpeaker."
      replyTo: "[...]"
      message: "You've been made an " + invite.role + " by " + name + '. <a href="' + baseUrl + 'register/' + invite.token + '" target="_blank" >Click here to setup your account and get started.</a>'
      inviter: name
      teamName: accountName
      role: invite.role
      inviteUrl: baseUrl + 'invitation/' + invite.token
      preview: "You've been invited to join " + accountName + " at PostSpeaker by " + name + ". Open this email to continue setting up your account."
      btnText: "Get started"
      template: Assets.getText 'Invitation.html'
```

I've logged out the options and all fields are correctly set. This exact code works fine in 1.1.x

**Comment by dr-dimitru** [comment]
@satyavh reproduced, solved. See [v1.2.2](https://github.com/VeliovGroup/Meteor-Mailer/releases/tag/1.2.2). Please let me know how it works on your end

**Comment by satyavh** [comment]
Email gets send now, so that's cool!
However the template {{ }} do not get populated

**Comment by satyavh** [comment]
Also, the email often gets send twice but that was already an issue with 1.1

**Comment by dr-dimitru** [comment]
@satyavh 

> However the template {{ }} do not get populated

Can not reproduce, and I don't see you using placeholders in your template

Works on my end, testing right now on mailing service, doesn't sent twice

**Comment by satyavh** [comment]
What do you mean you don't see me using placeholders in my template? I definitely have placeholders in my template and they were working fine in 1.1 :-)

About the sending twice, I'll dive into it. But it def happens for me

**Comment by satyavh** [comment]
Sending twice might be caused by Meteor.defer / the interval. Sending takes time, and while it is sending the interval (queueTry ) might run again, causing it to be sent twice. Something like that...

**Comment by dr-dimitru** [comment]
@satyavh `intervalTime: 5`, 5 seconds may be not enough to complete SMTP session.
Could you please show you template with placeholders and how you define helpers?

**Comment by dr-dimitru** [comment]
what `Assets.getText 'Invitation.html'` returns?

```
console.log Assets.getText 'Invitation.html'
```

**Comment by satyavh** [comment]
Found it, line 163/169, your regex doesn't support camelCase and excludes quite a lot of characters. I feel this is a better regex, excepting anything between {{ and }}

`matchStr  = string.match /\{{2}\s?([\s\S]+?)\s?\}{2}/g`

alternatively:
matchStr  = string.match /{{2}\s?([a-zA-Z0-9-_]+)\s?}{2}/g

**Comment by dr-dimitru** [comment]
Okay, I guess never used it with uppercase letters. Thank you for investigation.
Tested, updated and published as [v1.2.3](https://github.com/VeliovGroup/Meteor-Mailer/releases/tag/1.2.3)

**Comment by satyavh** [comment]
Awesome, it works like a charm again!

**Comment by dr-dimitru** [comment]
@satyavh thank you sir for the help with investigation.
