### ISSUE TITLE
Let's add plain-text version

### ISSUE THREAD

**Issue by satyavh** [VeliovGroup/Meteor-Mailer#5]
Meteor email package enables adding plain-text to an email:

```
text, html String
Mail body (in plain text and/or HTML)
```

But this package does not implement it. Not sending a plain-text version decreases SpamAssassin's score by -1 (!) decreasing deliverability. 

```
          Email.send
                from: if !!~_self.login.indexOf('@') then "<#{_self.login}> #{_self.accountName}" else "<#{_self.login}@#{_self.host}> #{_self.accountName}"
                to:      letter.to
                cc:      letter.opts?.cc
                bcc:     letter.opts?.bcc
                replyTo: letter.opts?.replyTo
                subject: letter.subject.replace /<(?:.|\n)*?>/gm, ''
                html:    _self.compileBody letter.opts, letter.template
```

I think this would be a great addition, and it should be very easy using a package like this: https://www.npmjs.com/package/html-to-text

Just posting this so you are aware of this.

**Comment by dr-dimitru** [comment]
Hello @satyavh ,

Thank you for suggestion, currently I'm on major update of this lib.
I'm planning to utilize `nodemailer` NPM package, which has feature suggested by you.

**Comment by satyavh** [comment]
That sounds really great! Will be looking for it

**Comment by dr-dimitru** [comment]
Hello @satyavh 

Sorry it took that long.
Plain-text version of letter now is supported, released as [`v2.0.0`](https://github.com/VeliovGroup/Meteor-Mailer/releases/tag/2.0.0)

Please be careful this lib has 100% new API.

Let me know what do you think.
Thank you for suggestion :)

**Comment by satyavh** [comment]
Wow this looks really impressive. Great job! 
I'm not familiar with nodemailer so I have some studying to do. Might be overkill for us, and of course there's the rewrite aspect. 

Also, we are already heavily invested in [meteor-job-collection](https://github.com/vsivsi/meteor-job-collection/), which I think (as far as I understand now from scanning the docs) could potentially solve the same problem that your queueing system solves. At least for single SMTP servers.
We actually already use it to schedule emails with Meteor Mailer. And if it fails, it retries sending.
So I think that's more the direction we would go now.

But still, impressive v2.0! 
Cheers!

**Comment by dr-dimitru** [comment]
Hello @satyavh ,

Thank you.

The main idea behind this - let developers to use mailer as a microservice, it shares only MongoDB and can ran on same or separate server.
Which is a better idea, when building mailer into the app.
And in general let your users keep receiving email even if UI (Meteor) is down, or having maintenance.

IMHO Meteor.js is good for UI, but business logic, long running tasks and etc. should be separated.
From now it comes as NPM package, so it really easy to use across apps and modules.

I've took a look on `vsivsi:job-collection` and it is very different from [`josk` package](https://www.npmjs.com/package/josk), which used in this package as underlying layer:
 - `job-collection` is Meteor only solution
 - `job-collection` is Isomorphic
 - While `josk` is NPM, and has simpler API

Anyways, thank you for feedback.
You can fork previous version of Meteor-Mailer, and I can send you a PR to add `plain-text` support.
