### ISSUE TITLE
Does Meteor-Mailer cover sending accounts related emails?

### ISSUE THREAD

**Issue by gibelium** [VeliovGroup/Meteor-Mailer#7]
### I'm having a very basic question

Does Meteor-Mailer cover sending accounts related emails?

We are using the [accounts-password](https://github.com/meteor/meteor/tree/devel/packages/accounts-password) package and in parallel we already use nodemailer for customer-related emails. I try to find a way to use nodemailer for all email sending tasks.

**Comment by gibelium** [comment]
Okay, I just took a closer look into the Meteor email implementation and the good news is, that it already uses nodemailer which is obviously configured via MAIL_URL.

To clarify my question: I like to define several SMTP transports within an application specific EmailSenderService and send the accounts related emails though one dedicated transport defined within the service. In general I like to get rid of the MAIL_URL as it is somehow misleading.

**Comment by gibelium** [comment]
I did ask the more or less same question at stackoverflow. Please find the answer here: [How to customise email transports](https://stackoverflow.com/questions/56620570/how-to-customise-email-transports)

**Comment by dr-dimitru** [comment]
@gibelium We're using this package to send all kind of emails from our meteor application.
To customize "sign up emails" we're using:
```js
Accounts.validateLoginAttempt((attempt) => {
  // Custom logic here
});
```

Everything else is custom made via standard *Meteor Methods*, including password reset.
